#!/usr/bin/env node
import { lstat, mkdir, readFile, readdir, rmdir, unlink, writeFile } from 'node:fs/promises';
import { dirname, isAbsolute, join, relative, resolve, sep } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const landingDirectory = dirname(fileURLToPath(import.meta.url));
const repositoryDirectory = dirname(landingDirectory);
const defaultOutput = join(landingDirectory, 'dist');
const sourceFiles = Object.freeze([
  'index.html',
  '404.html',
  '_headers',
  'robots.txt',
  'sitemap.xml',
  'assets/styles.css',
  'assets/copy.js',
  'assets/favicon.svg',
]);
const installerFiles = Object.freeze(['install.sh', 'install.ps1']);
const outputFiles = [...sourceFiles, ...installerFiles];
const markerName = '.pairmux-landing-output';
const markerContent = 'pairmux landing generated output v1\n';

function contains(parent, child) {
  const path = relative(parent, child);
  return path === '' || (!isAbsolute(path) && path !== '..' && !path.startsWith(`..${sep}`));
}

async function statIfPresent(path) {
  try {
    return await lstat(path);
  } catch (error) {
    if (error.code === 'ENOENT') return null;
    throw error;
  }
}

async function rejectSymlinkAncestors(path) {
  let current = path;
  while (true) {
    const stat = await statIfPresent(current);
    if (stat?.isSymbolicLink()) {
      throw new Error(`Refusing a symlink in the output path: ${current}`);
    }
    const parent = dirname(current);
    if (parent === current) return;
    current = parent;
  }
}

async function inspectOutput(outputDirectory) {
  await rejectSymlinkAncestors(outputDirectory);
  const stat = await statIfPresent(outputDirectory);
  if (!stat) return [];
  if (!stat.isDirectory()) throw new Error('Output must be a directory.');

  const entries = await readdir(outputDirectory);
  if (entries.length === 0) return [];

  const marker = join(outputDirectory, markerName);
  const markerStat = await statIfPresent(marker);
  if (!markerStat?.isFile() || (await readFile(marker, 'utf8')) !== markerContent) {
    throw new Error('Refusing to clean a non-empty output directory not generated by this build.');
  }

  const allowedRootEntries = new Set([
    ...outputFiles.filter((file) => !file.includes('/')),
    'assets',
    markerName,
  ]);
  const allowedAssets = new Set(sourceFiles.filter((file) => file.startsWith('assets/')).map((file) => file.slice(7)));
  const existingFiles = [];

  for (const entry of entries) {
    if (!allowedRootEntries.has(entry)) {
      throw new Error(`Refusing to clean unexpected output entry: ${entry}`);
    }
    const entryPath = join(outputDirectory, entry);
    const entryStat = await lstat(entryPath);
    if (entry === 'assets') {
      if (!entryStat.isDirectory() || entryStat.isSymbolicLink()) {
        throw new Error('Output assets must be a real directory.');
      }
      for (const asset of await readdir(entryPath)) {
        const assetStat = await lstat(join(entryPath, asset));
        if (!allowedAssets.has(asset) || !assetStat.isFile() || assetStat.isSymbolicLink()) {
          throw new Error(`Refusing to clean unexpected output asset: ${asset}`);
        }
        existingFiles.push(`assets/${asset}`);
      }
    } else {
      if (!entryStat.isFile() || entryStat.isSymbolicLink()) {
        throw new Error(`Refusing to replace a non-regular output file: ${entry}`);
      }
      if (entry !== markerName) existingFiles.push(entry);
    }
  }

  return existingFiles;
}

/** Build an allowlisted, dependency-free static site; canonical installers are copied verbatim. */
export async function buildSite({
  outputDir = defaultOutput,
  sourceDir = join(landingDirectory, 'src'),
  installerRoot = repositoryDirectory,
} = {}) {
  const outputDirectory = resolve(outputDir);
  const sourceDirectory = resolve(sourceDir);
  const installerDirectory = resolve(installerRoot);

  if (contains(repositoryDirectory, outputDirectory) && outputDirectory !== defaultOutput) {
    throw new Error('Inside this repository, output is restricted to landing/dist.');
  }
  if (contains(outputDirectory, landingDirectory) || contains(outputDirectory, sourceDirectory) || contains(sourceDirectory, outputDirectory)) {
    throw new Error('Output must not contain build inputs or be inside the source directory.');
  }

  const inputs = [
    ...sourceFiles.map((file) => ({ input: join(sourceDirectory, file), output: file })),
    ...installerFiles.map((file) => ({ input: join(installerDirectory, file), output: file })),
  ];

  // Read every required input before touching existing output. Missing inputs fail closed.
  const contents = [];
  for (const { input, output } of inputs) {
    if (contains(outputDirectory, input)) throw new Error('Output must not contain a build input.');
    const inputStat = await lstat(input).catch((error) => {
      throw new Error(`Missing or unreadable build input: ${input}`, { cause: error });
    });
    if (!inputStat.isFile() || inputStat.isSymbolicLink() || inputStat.size === 0) {
      throw new Error(`Build input must be a non-empty regular file: ${input}`);
    }
    contents.push({ output, data: await readFile(input) });
  }

  const existingFiles = await inspectOutput(outputDirectory);
  await mkdir(outputDirectory, { recursive: true });
  await writeFile(join(outputDirectory, markerName), markerContent);

  // Never recursively remove the output tree: unlink only checked, generated files.
  for (const file of existingFiles) await unlink(join(outputDirectory, file));
  if (await statIfPresent(join(outputDirectory, 'assets'))) {
    await rmdir(join(outputDirectory, 'assets'));
  }
  await mkdir(join(outputDirectory, 'assets'));
  for (const { output, data } of contents) {
    await writeFile(join(outputDirectory, output), data);
  }

  return { outputDir: outputDirectory, files: [...outputFiles] };
}

async function run() {
  const args = process.argv.slice(2);
  if (args.length > 0 && (args.length !== 2 || args[0] !== '--out-dir' || !args[1])) {
    throw new Error('Usage: node landing/build.mjs [--out-dir <empty-or-generated-directory>]');
  }
  const result = await buildSite(args.length ? { outputDir: args[1] } : undefined);
  console.log(`Built ${result.files.length} static files in ${result.outputDir}`);
}

if (process.argv[1] && pathToFileURL(resolve(process.argv[1])).href === import.meta.url) {
  run().catch((error) => {
    console.error(`Landing build failed: ${error.message}`);
    process.exitCode = 1;
  });
}
